title: "Введение в практические методы оптимизации"
url: "https://sber219.fmin.xyz"
logo: "/images/logo.svg"

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "fmin.xyz":
    - "https://fmin.xyz"
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all

theme: jekyll-theme-cayman
